---
- name: Deploy LEMP stack and WordPress
  hosts: webservers
  become: yes
  vars:
    php_version: "8.1"
    mysql_root_password: "Admin123#"  # Replace with your actual MySQL root password
    mysql_user_password: "admin123"

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install MySQL Python module
      apt:
        name: python3-mysqldb
        state: present

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Install PHP and required extensions
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php-fpm
        - php-mysql
        - php-cli
        - php-gd
        - php-curl

    - name: Configure Nginx for WordPress
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Create MySQL database for WordPress
      mysql_db:
        name: waqasdatabase
        state: present

    - name: Create MySQL user for WordPress
      mysql_user:
        name: waqas
        password: "{{ mysql_user_password }}"
        priv: "*.*:ALL"
        host: localhost
        state: present

    - name: Reload MySQL service using systemd
      systemd:
        name: mysql
        state: restarted
      become: yes

    - name: Download and extract WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress archive
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes
      notify: Restart PHP-FPM

    - name: Set ownership and permissions for WordPress
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart PHP-FPM
      service:
        name: php{{ php_version }}-fpm
        state: restarted

